FROM node:20-alpine AS build
WORKDIR /app
COPY admin/frontend/package.json ./
RUN npm install
COPY admin/frontend .
RUN npm run build

FROM nginx:stable-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
